### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by mzielinskim** [mjpitz/orthostatic#1]
I'm trying to build yiur app for my Garmin fenix 6x burt i only get these errors without further explaination

Error: Unexpected Type Error
Details: Failed invoking <symbol>
Stack: 
  - median() at D:\garmin\orthostatic-main\source\LastView.mc:44 0x10000728 
  - onLayout() at D:\garmin\orthostatic-main\source\LastView.mc:31 0x10000540 
  -

**Comment by mjpitz** [comment]
I suspect this is due to empty data. I thought I had accounted for that. Let me take a look. If something stands out to you, let me know

**Comment by mjpitz** [comment]
Added a null check which should resolve the issue @mzielinskim came across.

**Comment by mzielinskim** [comment]
It would be great to have a fownloadable file for the garmin . ( even better if you would upload it to garmin connect iq store)

Greetings
Michael
